ulimit -n 2048
python -u ./experiment.py --dataset compas
python -u ./experiment.py --dataset diamonds
python -u ./experiment.py --dataset house_sales
python -u ./experiment.py --dataset bike_sharing
python -u ./experiment.py --dataset electricity
python -u ./experiment.py --dataset eye_movements
python -u ./experiment.py --dataset telescope
python -u ./experiment.py --dataset diabetes
python -u ./experiment.py --dataset credit
python -u ./experiment.py --dataset california
python -u ./experiment.py --dataset heloc
python -u ./experiment.py --dataset road_safety
python -u ./experiment.py --dataset brazilian_houses
python -u ./experiment.py --dataset abalone
python -u ./experiment.py --dataset supreme
python -u ./experiment.py --dataset seattle_crime
python -u ./experiment.py --dataset superconduct
python -u ./experiment.py --dataset wine_quality
python -u ./experiment.py --dataset medical_charges
python -u ./experiment.py --dataset jannis
python -u ./experiment.py --dataset defaults
python -u ./experiment.py --dataset bioresponse
python -u ./experiment.py --dataset mercedes
python -u ./experiment.py --dataset sgemm
python -u ./experiment.py --dataset topo
python -u ./experiment.py --dataset ailerons
python -u ./experiment.py --dataset miami_housing
python -u ./experiment.py --dataset cpu
python -u ./experiment.py --dataset elevators
python -u ./experiment.py --dataset house
python -u ./experiment.py --dataset houses
python -u ./experiment.py --dataset pol
python -u ./experiment.py --dataset sulfur
python -u ./experiment.py --dataset miniboone
python -u ./experiment.py --dataset bank_marketing
python -u ./experiment.py --dataset yprop
python -u ./experiment.py --dataset ukair
python -u ./experiment.py --dataset allstate
python -u ./experiment.py --dataset albert
python -u ./experiment.py --dataset airlines
python -u ./experiment.py --dataset covertype
python -u ./experiment.py --dataset higgs
python -u ./experiment.py --dataset nyc_taxi
python -u ./experiment.py --dataset soil
python -u ./experiment.py --dataset kickstarter
python -u ./experiment.py --dataset clothing
python -u ./experiment.py --dataset streetview
python -u ./experiment.py --dataset skin_cancer
python -u ./experiment.py --dataset xor_blobs