# --------------------
# XOR blobs synthetic
# --------------------
xor_blobs:
  WHICH_DEVICE: 'cpu' 
  N_WORKERS: 0 
  NO_REPLICATES: 5
  MODEL_TYPES: 
  - CLIP
  - GMC
  - MCN    
  - ICEH  
  PHI_DIMS: [4, 4]    
  HIDDEN_DIM: 4
  LATENT_DIMS: [2, 3, 4]  
  BATCH_SIZES: [16, 32, 64]  
  LEARNING_RATES: [0.001, 0.002, 0.003, 0.005, 0.01, 0.02, 0.03, 0.05]
  EPOCHS: 20
  VERBOSITY : 1


# ------------------------
# Purely tabular datasets
# ------------------------
compas:
  WHICH_DEVICE: 0  
  N_WORKERS: 0
  NO_REPLICATES : 5
  MODEL_TYPES:   
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH  
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

diamonds:
  WHICH_DEVICE: 1  
  N_WORKERS: 8
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

house_sales:
  WHICH_DEVICE: 2  
  N_WORKERS: 10
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH 
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

bike_sharing:
  WHICH_DEVICE: 3  
  N_WORKERS: 0
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH 
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

electricity:
  WHICH_DEVICE: 0  
  N_WORKERS: 8
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH 
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

eye_movements:
  WHICH_DEVICE: 1  
  N_WORKERS: 0 
  NO_REPLICATES : 5
  MODEL_TYPES:
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128  
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

telescope:
  WHICH_DEVICE: 2  
  N_WORKERS: 0
  NO_REPLICATES : 5
  MODEL_TYPES:
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH 
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

diabetes:
  WHICH_DEVICE: 3  
  N_WORKERS: 10
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH 
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

credit:
  WHICH_DEVICE: 0  
  N_WORKERS: 8
  NO_REPLICATES : 5
  MODEL_TYPES:
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH 
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

california:
  WHICH_DEVICE: 1  
  N_WORKERS: 4
  NO_REPLICATES : 5
  MODEL_TYPES:
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH  
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

heloc:
  WHICH_DEVICE: 2
  N_WORKERS: 8
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH 
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

road_safety:
  WHICH_DEVICE: 3
  N_WORKERS: 12
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - GMC   
  - ICEH 
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100 
  BATCH_SIZES: [4096]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [16, 32, 64] 
  VERBOSITY : 1

brazilian_houses:
  WHICH_DEVICE: 0  
  N_WORKERS: 0
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH 
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

abalone:
  WHICH_DEVICE: 1
  N_WORKERS: 0
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

supreme:
  WHICH_DEVICE: 2  
  N_WORKERS: 0
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

seattle_crime:
  WHICH_DEVICE: 3  
  N_WORKERS: 10
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

superconduct:
  WHICH_DEVICE: 0  
  N_WORKERS: 8
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - GMC   
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [16, 32] 
  VERBOSITY : 1

wine_quality:
  WHICH_DEVICE: 1  
  N_WORKERS: 0
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

medical_charges:
  WHICH_DEVICE: 2 
  N_WORKERS: 12
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [4096]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

jannis:
  WHICH_DEVICE: 3 
  N_WORKERS: 12
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - GMC   
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [16, 32, 64] 
  VERBOSITY : 1

defaults:
  WHICH_DEVICE: 0
  N_WORKERS: 6
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

bioresponse:
  WHICH_DEVICE: 1  
  N_WORKERS: 6
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - GMC   
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [16, 32] 
  VERBOSITY : 1

mercedes:
  WHICH_DEVICE: 2 
  N_WORKERS: 6
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - GMC   
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64] 
  VERBOSITY : 1

sgemm:
  WHICH_DEVICE: 3  
  N_WORKERS: 12
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [4096]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

topo:
  WHICH_DEVICE: 0  
  N_WORKERS: 8
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - GMC   
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64] 
  VERBOSITY : 1

ailerons:
  WHICH_DEVICE: 1
  N_WORKERS: 8
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

miami_housing:
  WHICH_DEVICE: 2  
  N_WORKERS: 6
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

cpu:
  WHICH_DEVICE: 3 
  N_WORKERS: 0 
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

elevators:
  WHICH_DEVICE: 0  
  N_WORKERS: 8
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

house:
  WHICH_DEVICE: 1  
  N_WORKERS: 10
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

houses:
  WHICH_DEVICE: 2  
  N_WORKERS: 4
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

pol:
  WHICH_DEVICE: 3 
  N_WORKERS: 6
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

sulfur:
  WHICH_DEVICE: 0  
  N_WORKERS: 0
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

miniboone:
  WHICH_DEVICE: 1  
  N_WORKERS: 14
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - GMC   
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [16, 32, 64] 
  VERBOSITY : 1

bank_marketing:
  WHICH_DEVICE: 2  
  N_WORKERS: 0
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

yprop:
  WHICH_DEVICE: 3  
  N_WORKERS: 6
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - GMC   
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [16, 32, 64] 
  VERBOSITY : 1

ukair:
  WHICH_DEVICE: 0  
  N_WORKERS: 14
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [4096]  
  LEARNING_RATES: [0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01]
  LATENT_DIMS: [32, 64, 128] 
  VERBOSITY : 1

allstate:
  WHICH_DEVICE: 1  
  N_WORKERS: 14
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - GMC  
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [2048]  
  LEARNING_RATES: [0.0001, 0.00017783, 0.00031623, 0.00056234, 0.001, 0.00177828, 0.00316228, 0.00562341, 0.01] # 10**[-4, -3.75, -3.5, -3.25, -3, -2.75, -2.5, -2.25, -2]
  LATENT_DIMS: [128, 64, 32] 
  VERBOSITY : 1

albert:
  WHICH_DEVICE: 2 
  N_WORKERS: 12
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - GMC 
  - ICEH   
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [2048]  
  LEARNING_RATES: [0.0001, 0.0001778279410038, 0.0003162277660168, 0.0005623413251903, 0.001, 0.0017782794100389, 0.0031622776601683, 0.0056234132519034, 0.01] # 10**[-4, -3.75, -3.5, -3.25, -3, -2.75, -2.5, -2.25, -2]
  LATENT_DIMS: [128, 64, 32]
  VERBOSITY : 1

airlines:
  WHICH_DEVICE: 3  
  N_WORKERS: 14
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH 
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [4096]  
  LEARNING_RATES: [0.0001, 0.0001778279410038, 0.0003162277660168, 0.0005623413251903, 0.001, 0.0017782794100389, 0.0031622776601683, 0.0056234132519034, 0.01] # 10**[-4, -3.75, -3.5, -3.25, -3, -2.75, -2.5, -2.25, -2]
  LATENT_DIMS: [128, 64, 32]
  VERBOSITY : 1

covertype:
  WHICH_DEVICE: 0  
  N_WORKERS: 14
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH 
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [4096]  
  LEARNING_RATES: [0.0001, 0.0001778279410038, 0.0003162277660168, 0.0005623413251903, 0.001, 0.0017782794100389, 0.0031622776601683, 0.0056234132519034, 0.01] # 10**[-4, -3.75, -3.5, -3.25, -3, -2.75, -2.5, -2.25, -2]
  LATENT_DIMS: [128, 64, 32]
  VERBOSITY : 10

higgs:
  WHICH_DEVICE: 1  
  N_WORKERS: 14
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - GMC 
  - ICEH 
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [4096]  
  LEARNING_RATES: [0.0001, 0.0001778279410038, 0.0003162277660168, 0.0005623413251903, 0.001, 0.0017782794100389, 0.0031622776601683, 0.0056234132519034, 0.01] # 10**[-4, -3.75, -3.5, -3.25, -3, -2.75, -2.5, -2.25, -2]
  LATENT_DIMS: [128, 64, 32] 
  VERBOSITY : 1

nyc_taxi:
  WHICH_DEVICE: 2  
  N_WORKERS: 14
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH 
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [4096]  
  LEARNING_RATES: [0.0001, 0.0001778279410038, 0.0003162277660168, 0.0005623413251903, 0.001, 0.0017782794100389, 0.0031622776601683, 0.0056234132519034, 0.01] # 10**[-4, -3.75, -3.5, -3.25, -3, -2.75, -2.5, -2.25, -2]
  LATENT_DIMS: [128, 64, 32] 
  VERBOSITY : 1

soil:
  WHICH_DEVICE: 3 
  N_WORKERS: 0
  NO_REPLICATES : 5
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH 
  PHI_DIMS: [128, 128]    
  HIDDEN_DIM: 128
  EPOCHS: 100
  BATCH_SIZES: [1024]  
  LEARNING_RATES: [0.0001, 0.0001778279410038, 0.0003162277660168, 0.0005623413251903, 0.001, 0.0017782794100389, 0.0031622776601683, 0.0056234132519034, 0.01] # 10**[-4, -3.75, -3.5, -3.25, -3, -2.75, -2.5, -2.25, -2]
  LATENT_DIMS: [128, 64, 32]
  VERBOSITY : 1

# ----------------------
# Text-tabular datasets
# ----------------------
kickstarter:
  WHICH_DEVICE: 0
  N_WORKERS: 12
  NO_REPLICATES : 3
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH            
  EPOCHS: 10
  PHI_DIMS: [512, 512]    
  HIDDEN_DIM: 512
  BATCH_SIZES: [256]
  LEARNING_RATES: [0.0001, 0.0001778279410038, 0.0003162277660168, 0.0005623413251903, 0.001, 0.0017782794100389, 0.0031622776601683, 0.0056234132519034, 0.01] # 10**[-4, -3.75, -3.5, -3.25, -3, -2.75, -2.5, -2.25, -2]
  LATENT_DIMS: [512, 256, 128]
  VERBOSITY : 10

clothing:
  WHICH_DEVICE: 0
  N_WORKERS: 12
  NO_REPLICATES : 3
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH           
  EPOCHS: 20
  PHI_DIMS: [512, 512]    
  HIDDEN_DIM: 512
  BATCH_SIZES: [128]
  LEARNING_RATES: [0.00025, 0.0005, 0.00075, 0.001, 0.0025, 0.005]
  LATENT_DIMS: [256, 128]
  VERBOSITY : 10


# -----------------------
# Image-tabular datasets
# -----------------------
streetview:
  WHICH_DEVICE: 1
  N_WORKERS: 12 
  NO_REPLICATES : 3
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH        
  EPOCHS: 50
  PHI_DIMS: [512, 512]    
  HIDDEN_DIM: 512    
  BATCH_SIZES: [512]    
  LEARNING_RATES: [0.0001, 0.00025, 0.0005, 0.00075, 0.001, 0.0025, 0.005, 0.0075, 0.01]
  LATENT_DIMS:  [512, 256, 128]  
  VERBOSITY : 1


skin_cancer:
  WHICH_DEVICE: 1
  N_WORKERS: 12    
  NO_REPLICATES : 3
  MODEL_TYPES: 
  - CONTROL    
  - SCARF 
  - SUBTAB
  - CLIP
  - GMC
  - MCN    
  - ICEH        
  EPOCHS: 50
  PHI_DIMS: [512, 512]    
  HIDDEN_DIM: 512     
  BATCH_SIZES: [512]    
  LEARNING_RATES: [0.0001, 0.00025, 0.0005, 0.00075, 0.001, 0.0025, 0.005, 0.0075, 0.01]
  LATENT_DIMS:  [512, 256, 128]  
  VERBOSITY : 1
